### ISSUE TITLE
Is there a stable version of LAMS 3.* and how to install it?

### ISSUE THREAD

**Issue by dnna** [lamsfoundation/lams#10]
Hello,

I have been looking at information about LAMS and want to install the latest stable version of it. However, all the documentation I could find has been either outdated or lackluster. Specifically, the most complete articles I have been able to find are:
https://wiki.lamsfoundation.org/display/lams/LAMS+3.1+in+Ubuntu
http://edutechwiki.unige.ch/en/LAMS_installation_and_configuration

Those pages, unfortunately, offer contradicting information regarding the server requirements (for example one says that JDK 8 is required while the other says JDK 11 is required) and the Ubuntu installation guide requests that we clone a branch that does not exist (https://github.com/lamsfoundation/lams/tree/v3.1). I tried manually downloading the `3.0` release from this repository, but that seems to be throwing errors like
`[javac] /app/lams/lams_common/src/java/org/lamsfoundation/lams/policies/dao/hibernate/PolicyDAO.java:22: error: package com.sun.webkit does not exist`
when trying to build it.

Because of this, I would like some help in clarifying the following questions:
* Is there is a stable version of LAMS 3+ that is usable and recommended for production? If so what version is it and how do we download it?
* Is there a guide with up-to-date instructions for how to build and run that version?

**Comment by erniegx** [comment]
Hi dnna, 

Sorry, I didn't see this until now! My apologies. 

3.1 is not longer supported, so I'd suggest you switch to version 4.0 or master. Both of them are stable for production use. 

Thank you
