### ISSUE TITLE
There seems to be hard-coded "localhost" in the base URL.

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#11]
I installed the LAMS 4.0 in Ubuntu 20.04 and Nginx as reverse proxy. But all the links are still in the form of //localhost/*** 
I found nowhere to configure this.
![image](https://user-images.githubusercontent.com/1741341/127253292-1169828c-f06b-40c1-aabc-c45943432630.png)
BTW: Many links are Javascript-triggered, which may be not a good practice.

**Comment by erniegx** [comment]
Two ways to fix this:

1) In your MySQL DB, change the lams_configuration row "ServerURL" to whatever your LAMS server is:

`UPDATE lams_configuration SET config_value = 'http://<<server-url>>/lams/' WHERE config_key = 'ServerURL';`

2) Login as sysadmin using localhost:8080/lams/ then Sysadmin menu -> Edit configuration Settings and set the Server URL there. 

Restart LAMS to make this change stick.

**Comment by fishfree** [comment]
@erniegx Thank you. It works!
