### ISSUE TITLE
Some components don't conform to the ServerURL and ServerURLContextPath

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#12]
For example, when I click preview in the authoring tool, it shows page not found:
![image](https://user-images.githubusercontent.com/1741341/128342760-a6ede733-e59c-4f4b-9a36-abf1962f7558.png)
![image](https://user-images.githubusercontent.com/1741341/128342622-84ad5a12-0314-4dcf-a042-d792e733081e.png)
![image](https://user-images.githubusercontent.com/1741341/128343078-f6d4f014-7b38-4a3d-a9eb-5a6f3b277193.png)
Some js files also have the same problem:
![image](https://user-images.githubusercontent.com/1741341/128343654-1a76db66-4de4-42af-943b-c7f2128305af.png)

I manually delete the repeated lams/ in the URL, it works:
![image](https://user-images.githubusercontent.com/1741341/128342970-29c7b118-0d38-4460-8f92-2f60b6ed1b98.png)

My ServerURL  is http://10.2.15.42/lams/, and ServerURLContextPath is lams/

**Comment by MarcinCieslak** [comment]
Hi,
can you execute
SELECT * FROM lams_configuration WHERE config_key LIKE 'ServerURL%';
in the DB and paste the result here?
Also if you made changes to the configuration via sysadmin console, can you restart the server?

**Comment by fishfree** [comment]
@MarcinCieslak I pasted my config in the issue. And this is the screenshot:
![image](https://user-images.githubusercontent.com/1741341/128429748-d122c342-5901-495c-bbfd-fbdfc4685ad3.png)
I restart the server for several times, no luck.

**Comment by MarcinCieslak** [comment]
Hi!
I just needed to make sure that you have got configuration set up correctly. 
Especially that I can not reproduce the issue. Everything works fine, both for 4.0, and 4.5 versions.
Can you doing the same (like preview in authoring) without changing the ServerURL, i.e. after a fresh LAMS build while there is still http://localhost:8080/lams/ there?
Also can you try setting up
http://10.2.15.42:80/lams/
as the ServerURL, i.e. add a port?

**Comment by fishfree** [comment]
@MarcinCieslak Thank you! I know where I was wrong. The code has no problem.
