### ISSUE TITLE
LDAP config page: 	org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: Session/EntityManager is closed

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#13]
When I access /lams/admin/ldap/start.do, it shows error as below:
`Sorry, there has been an error.
There is a problem processing this request. Close the browser window and try again.
If the problem persists please contact your system administrator.
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: Session/EntityManager is closed
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: Session/EntityManager is closed at org.springframework@4.3.12.RELEASE//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) at org.springframework@4.3.12.RELEASE//org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) at javax.servlet.api@1.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:686) at org.springframework@4.3.12.RELEASE//org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) at javax.servlet.api@1.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:791) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.owasp.csrfguard@3.1.0-SNAPSHOT//org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:80) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at org.springframework@4.3.12.RELEASE//org.springframework.orm.hibernate5.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151) at org.springframework@4.3.12.RELEASE//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at deployment.lams.ear//org.lamsfoundation.lams.web.filter.LocaleFilter.doFilterInternal(LocaleFilter.java:114) at org.springframework@4.3.12.RELEASE//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at deployment.lams.ear//org.lamsfoundation.lams.web.session.SystemSessionFilter.doFilter(SystemSessionFilter.java:59) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at org.wildfly.extension.undertow@14.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78) at io.undertow.core@2.0.13.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.core@2.0.13.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53) at io.undertow.core@2.0.13.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59) at io.undertow.core@2.0.13.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.core@2.0.13.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50) at io.undertow.core@2.0.13.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.core@2.0.13.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at org.wildfly.extension.undertow@14.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) at io.undertow.core@2.0.13.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at org.wildfly.extension.undertow@14.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68) at io.undertow.core@2.0.13.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at org.wildfly.extension.undertow@14.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) at org.wildfly.extension.undertow@14.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) at org.wildfly.extension.undertow@14.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) at org.wildfly.extension.undertow@14.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) at org.wildfly.extension.undertow@14.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) at io.undertow.servlet@2.0.13.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) at io.undertow.core@2.0.13.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:360) at io.undertow.core@2.0.13.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) at org.jboss.threads@2.3.2.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985) at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487) at org.jboss.threads@2.3.2.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.lang.IllegalStateException: Session/EntityManager is closed at org.hibernate@5.3.6.Final//org.hibernate.internal.AbstractSharedSessionContract.checkOpen(AbstractSharedSessionContract.java:357) at org.hibernate@5.3.6.Final//org.hibernate.engine.spi.SharedSessionContractImplementor.checkOpen(SharedSessionContractImplementor.java:138) at org.hibernate@5.3.6.Final//org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:697) at org.hibernate@5.3.6.Final//org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23) at deployment.lams.ear//org.lamsfoundation.lams.dao.hibernate.LAMSBaseDAO.convertLegacyStyleParameters(LAMSBaseDAO.java:495) at deployment.lams.ear//org.lamsfoundation.lams.dao.hibernate.LAMSBaseDAO.doFind(LAMSBaseDAO.java:474) at deployment.lams.ear//org.lamsfoundation.lams.dao.hibernate.LAMSBaseDAO.find(LAMSBaseDAO.java:309) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.springframework@4.3.12.RELEASE//org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) at org.springframework@4.3.12.RELEASE//org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) at org.springframework@4.3.12.RELEASE//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) at org.springframework@4.3.12.RELEASE//org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) at org.springframework@4.3.12.RELEASE//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework@4.3.12.RELEASE//org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) at deployment.lams.ear.lams-tool-lapixl10.war//com.sun.proxy.$Proxy89.find(Unknown Source) at deployment.lams.ear//org.lamsfoundation.lams.usermanagement.service.UserManagementService.getFindIntegerResult(UserManagementService.java:996) at deployment.lams.ear//org.lamsfoundation.lams.usermanagement.service.UserManagementService.getCountUsers(UserManagementService.java:992) at deployment.lams.ear.lams-tool-lapixl10.war//org.lamsfoundation.lams.usermanagement.service.UserManagementService$$FastClassBySpringCGLIB$$aa86f00b.invoke(<generated>) at org.springframework@4.3.12.RELEASE//org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) at org.springframework@4.3.12.RELEASE//org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) at org.springframework@4.3.12.RELEASE//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) at org.springframework@4.3.12.RELEASE//org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) at org.springframework@4.3.12.RELEASE//org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) at org.springframework@4.3.12.RELEASE//org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) at org.springframework@4.3.12.RELEASE//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at deployment.lams.ear//org.lamsfoundation.lams.web.filter.TransactionRetryInterceptor.invoke(TransactionRetryInterceptor.java:61) at org.springframework@4.3.12.RELEASE//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework@4.3.12.RELEASE//org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) at deployment.lams.ear.lams-tool-lapixl10.war//org.lamsfoundation.lams.usermanagement.service.UserManagementService$$EnhancerBySpringCGLIB$$14e983f0.getCountUsers(<generated>) at deployment.lams.ear//org.lamsfoundation.lams.admin.web.controller.LdapConfigController.getNumLdapUsers(LdapConfigController.java:142) at deployment.lams.ear//org.lamsfoundation.lams.admin.web.controller.LdapConfigController.execute(LdapConfigController.java:84) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.springframework@4.3.12.RELEASE//org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:180) at org.springframework@4.3.12.RELEASE//org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440) at org.springframework@4.3.12.RELEASE//org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428) at org.springframework@4.3.12.RELEASE//org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) at org.springframework@4.3.12.RELEASE//org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) at org.springframework@4.3.12.RELEASE//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ... 62 more`

My LAMS is 4.0 branch. Missing LDAP depedencies in the build.xml?

**Comment by MarcinCieslak** [comment]
A good find, thank you!
Just fixed it.

**Comment by fishfree** [comment]
@MarcinCieslak Thank you, now the LDAP config page can show up. When fill the form and click the save button, however, a blank page shows up, and the HTML source is also blank. I checked the /wildfly/standalone/log/lams.log, it shows:
` WARNING Owasp.CsrfGuard - CSRF attack (user: sysadmin, ip: 127.0.0.1, uri: /lams/admin/config/save.do, error: Required Token is missing from the Request)`

**Comment by MarcinCieslak** [comment]
Fixed. Give it a go.
LDAP for LAMS is not widely used. If you bump into any other problems, please let us know.

**Comment by fishfree** [comment]
@MarcinCieslak Thank you!  I will re-compile it. However, could you tell me how to upgrade with the re-compiled package instead of overwriting the running instance?

**Comment by MarcinCieslak** [comment]
There is no automated way to do it.
First you need to figure out in which LAMS module the changes have been applied. For this particular issue you need to:
- go to lams_admin
- run Ant task deploy-jar (because there were changes in Java files in this module)
- run Ant task deploy-war (because there were changes in JSP files in this module)
- restart server
If the server you are building locally is not the one you are running production LAMS, then you need to manually copy lams-admin.jar and lams-admin.war from lams.ear directory on the local server.

**Comment by fishfree** [comment]
@MarcinCieslak Thank you very much. It worked.
