### ISSUE TITLE
What's the Lokalise URL of this project?

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#14]
In the README file, it says: 
For translating and internationalising LAMS, we use Lokalise. Lokalise is a fantastic localization and translation management software tool.

But no specific Lokalise project URL provided. We want the help translate this project.

**Comment by MarcinCieslak** [comment]
Thank you, that is very kind of you!
I understand that we are talking about the Chinese language?
@erniegx can you pick it up?

**Comment by erniegx** [comment]
Hi @fishfree  we do have Chinese translations but it's far for completed. If I'm not mistaken only about 30% of the LAMS labels have been translated to Chinese. 

We use Lokalise to manage our translations. If you want to participate in the translations for Chinese, please email me and I can set you up with it. 

Thanks

**Comment by fishfree** [comment]
@erniegx I don't know your email. Mine is winofchina#hotmail.com
