### ISSUE TITLE
doku tool seems missing in the 4.5 branch

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#16]
There is no Doku tool in the Authoring interface. When importing a course package authored in LAMS 3.2, it says: `The activity with signature ladoku11 is skipped because a matching tool cannot be found.` On the /lams/admin/toolcontentlist/start.do page, I found no such configurations either.
I'm not very familiar with LAMS. It seems to be dependent on Etherpad lite service?
My LAMS is built on 23 August, 2021 with pulling the code that day.

**Comment by fishfree** [comment]
The same issue is for the Whiteboard tool:
![94d7098b47415bf130698ecd2a671d1](https://user-images.githubusercontent.com/1741341/132632426-f61e2eed-1c25-4598-82fb-471468dd30d2.jpg)

**Comment by MarcinCieslak** [comment]
Hi!
doKu and Whiteboard depend on 3rd party software, so we made them optional tools and not included into standard LAMS build. If you want to use them, first follow 
/lams_build/conf/etherpad/readme.txt
and
/lams_build/conf/whiteboard/readme.txt

Then run "deploy" Ant target from
/lams_tool_doku/build.xml
and
/lams_tool_whiteboard/build.xml

Then start LAMS server.
Then you need to set up Etherpad settings in sysadmin "Edit configuration settings"
![image](https://user-images.githubusercontent.com/2900734/132646875-3777ab71-dde7-4aae-b714-a7aacb700283.png)
and Whiteboard settings in sysadmin "Tool management" -> "Whiteboard"

**Comment by fishfree** [comment]
@MarcinCieslak Thank you! After I run `ant deploy-jar && ant deploy-war`, both are built successfully and copied to the LAMS runnning folder, but there is still no Whiteboard on the tool management page. What's the problem?

**Comment by MarcinCieslak** [comment]
You need to run "deploy-tool", not "deploy" (sorry). The ones you run are not enough.

**Comment by fishfree** [comment]
@MarcinCieslak Thank you! Whiteboard now can work. But for Etherpad, I'm confused by the instructions in the readme.txt:
```
----------Same domain policy---------
Etherpad server should be installed on the same domain as LAMS server.
Although it's possible to install it on another subdomain, it has a few limitations in terms of format of supported domain names.
Let's say domain name is domain.tld, then:
* tld part of the domain name should consist of only one part (e.g. lams.com, lams.au)
* if we need to support more complex tld parts (e.g. lams.com.ru) it needs to be added to the hardcoded regex in Java code - https://code.lamsfoundation.org/fisheye/browse/lams/lams_tool_doku/src/java/org/lamsfoundation/lams/tool/dokumaran/service/DokumaranService.java?hb=true#to892
Currently only complex tlds of Singapore, Australia and UK are added to this regex.
** If we will decide to start supporting all possible domain tlds in the future - we will need to download full tld list (https://publicsuffix.org/list/effective_tld_names.dat)
and make use of it using 3rd party Java library https://github.com/whois-server-list/public-suffix-list
```
Questions:

1. There is no tld code lines in https://github.com/lamsfoundation/lams/blob/v4.5/lams_tool_doku/src/java/org/lamsfoundation/lams/tool/dokumaran/service/DokumaranService.java correspondent to https://code.lamsfoundation.org/fisheye/browse/lams/lams_tool_doku/src/java/org/lamsfoundation/lams/tool/dokumaran/service/DokumaranService.java?hb=true#to892
2. Are lams.example.com and etherpad.example.com the same domain?

**Comment by fishfree** [comment]
@MarcinCieslak I guess you've drop the hard-coded restrctions in the 4.5 branch but don't upgrade the readme.txt.
Now, I get my etherpad-lite standalonly working strictly according to your readme.txt. But doKu cannot work, as the screenshot below:
![image](https://user-images.githubusercontent.com/1741341/133518345-0682669a-e4e1-4110-a1d6-66f0a101be69.png)

**Comment by fishfree** [comment]
@MarcinCieslak Hi, Marcin, finally I found the file here: lams_common/src/java/org/lamsfoundation/lams/etherpad/service/EtherpadService.java. I changed the hard-coded top domain name. But I don't know how to compile and deploy without losting running data.

**Comment by MarcinCieslak** [comment]
Hi!
While readme.txt from line #70 mentions limitations to domains, it points to a wrong Java file - thanks for pointing it out. We will update it eventually.
If you can suggest a regex which is more inclusive (I guess you added China?), feel free to make a pull request or paste code here. We will be happy to include it.

To deploy your changes to EtherpadService:
1. Stop the server
2. Run "deploy-jar" from lams_common project. It will deploy lams.jar to lams.ear/lib directory on the server.
3. Start the server

**Comment by fishfree** [comment]
@MarcinCieslak Thank you very much! BTW: would you please add a Dockerfile or evern a docker-compose.yml?

**Comment by MarcinCieslak** [comment]
Maybe at some stage :)
