### ISSUE TITLE
How to change some interface translation text without recompiling the source?

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#18]
Esp. the copyright in the footer. It's so awful not to be able to change interface translations from admin UI or database.

**Comment by MarcinCieslak** [comment]
Why would you want to change copyright information? You are obliged by the license to leave it as is.

**Comment by fishfree** [comment]
> Why would you want to change copyright information? You are obliged by the license to leave it as is.

Because the Chinese translation is attributed to the earliest translator, not you.

**Comment by MarcinCieslak** [comment]
Oh, you mean copyright information for translation, not for LAMS as a product? Where do you have this copyright information? Can you provide a screenshot?

**Comment by erniegx** [comment]
@fishfree I think I know what you mean. 
If I'm not mistaken the previous Chinese translator perhaps accidentally assigned the copyright to a Chinese University. 

I believe I have [rectified](https://app.lokalise.com/project/158798415f0eae172b3263.88948345/?view=single&reference_lang_id=611&single_lang_id=602&search=msg.LAMS.copyright.short) this now in Lokalise. This label refers to LAMS software license though, so it should be the LAMS Foundation. 

If I'm not mistaken, you and your colleagues have full access to translate all the labels in LAMS via Lokalise. So feel free to translate these accordingly. As we've been doing pretty much every week, we have been updating them when new translations are added. 

Thanks

**Comment by erniegx** [comment]
@fishfree you don't have to recompile LAMS to change labels.

For instance if you want to change a label for say the Forum tool in Chinese, go to your _lams.ear_ folder. Then go to _lams-dictionary.jar/org/lamsfoundation/lams/tool/forum_, find the file that contains the labels in Simplified Chinese (_ApplicationResources_zh_CN.properties_) and you can edit the labels accordingly. 

Now, in order for these to take effect, you will need to restart the appserver though. But no need to recompile LAMS. 

Thanks

**Comment by fishfree** [comment]
@erniegx Thank you, Sir!

> @fishfree you don't have to recompile LAMS to change labels.
> 
> For instance if you want to change a label for say the Forum tool in Chinese, go to your _lams.ear_ folder. Then go to _lams-dictionary.jar/org/lamsfoundation/lams/tool/forum_, find the file that contains the labels in Simplified Chinese (_ApplicationResources_zh_CN.properties_) and you can edit the labels accordingly.
> 
> Now, in order for these to take effect, you will need to restart the appserver though. But no need to recompile LAMS.
> 
> Thanks
