### ISSUE TITLE
Is it necessary to forbid using digits in firstname or lastname?

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#20]
In my LMS, it is required to use students' campus numbers as lastname, fullname as firstname. When accessing LAMS from LMS, LAMS says `Can't create user due to validation error: Last name contains invalid characters`.
If it is NOT necessary, please change the validation Regex.

**Comment by MarcinCieslak** [comment]
![image](https://user-images.githubusercontent.com/2900734/170836076-bb0c855b-a86c-4eeb-97e8-6ebe12409800.png)

These options in sysadmin panel should help.

**Comment by fishfree** [comment]
@MarcinCieslak Thank you very much! Sorry for my unskillfulness.
