### ISSUE TITLE
Mindmap grouped activity bug

### ISSUE THREAD

**Issue by dnna** [lamsfoundation/lams#22]
Hello,

I have noticed a bug that prevents both the student and the teacher from viewing the mindmap of a grouped activity. Specifically when expanding one of the iframes it will return 404 Not found due to a typo in the below code:

https://github.com/lamsfoundation/lams/blob/45abd8fb5701761386ec30cd2478e55274ad081b/lams_tool_mindmap/web/pages/monitoring/summary.jsp#L271

The code should be
`data-src`
instead of 
`data-src=`

A few lines below for non-grouped activities it is correct:
https://github.com/lamsfoundation/lams/blob/45abd8fb5701761386ec30cd2478e55274ad081b/lams_tool_mindmap/web/pages/monitoring/summary.jsp#L275

**Comment by MarcinCieslak** [comment]
Hi!
Sorry for a late reply.
You are absolutely right.
It is fixed now.
Thank you!
