### ISSUE TITLE
When adding a user to a subgroup they can't see lessons that were created prior to their entry

### ISSUE THREAD

**Issue by dnna** [lamsfoundation/lams#25]
Hello,

I have noticed an issue where when we add a user to a subgroup as a learner, the table `lams_user_group` is not updated, which makes them unable to access any of the activities present in that subgroup prior to their entry into the group. If the user was present in the group as a learner, prior to the lesson being created, then access seems to be inherited correctly and they can view and interact with it.

Is this behavior intended? Is there a way to allow learners of a subgroup to have access to all lessons of that subgroup regardless of the time those lessons were created?

**Comment by MarcinCieslak** [comment]
Hi!
We have added this feature which should address the issue you described
https://lamsbugs.atlassian.net/browse/LDEV-5383
