### ISSUE TITLE
Is there a way to export all the learning records for learning analytics?

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#26]
Although there are Analytics operations in every course, it's not easy to export all the learning records in all courses. Thanks!

**Comment by MarcinCieslak** [comment]
Hi! 
Do you mean a LAMS-wide export of all course gradebooks, like this one
![image](https://user-images.githubusercontent.com/2900734/230897338-23cf442b-549d-4ecf-909f-9f1d19cb4f64.png)
or by "learning analytics" you mean question analytics in Question Bank like this one
![image](https://user-images.githubusercontent.com/2900734/230897707-2a22a1b4-bc08-49db-ab98-57a39eff76b1.png)
?

**Comment by fishfree** [comment]
@MarcinCieslak No. I mean all the learning activites logs.

**Comment by MarcinCieslak** [comment]
@fishfree 
OK. I am pretty sure you do not have in mind server logs, so I am going to need a screenshot of how you generate/access those "learning activities logs".

**Comment by erniegx** [comment]
@fishfree check out the sysadmin menu. Under Audit logs you will be able to see when students have started and completed for a given lesson(s). 

As @MarcinCieslak mentioned as well, you can export analytics from Gradebook and/or from each activity (in monitor). 

Learning analytics is a very broad and widely defined. But perhaps you can give us a bit more context as to what type of analytics you require?

**Comment by fishfree** [comment]
@MarcinCieslak @erniegx Thank you for your tips.
