### ISSUE TITLE
How to change DB connection strings in a production instance?

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#28]
I mean, I need to migrate the DB to a seperate server, then in which file of the production LAMS instance to modify the DB connection strings without recompilation?

**Comment by MarcinCieslak** [comment]
Hi!
Please look in
<WILDFLY_SERVER_PATH>/standalone/configuration/standalone.xml

**Comment by fishfree** [comment]
@MarcinCieslak Thank you very much, Marcin!
