### ISSUE TITLE
❓ how can i build this project in my pc?

### ISSUE THREAD

**Issue by LeeKonyu** [lamsfoundation/lams#29]
Hi,

I want to know how to build this project, please tell me the detailed steps to deploy the project.

Thank you.

Best,
Ky

**Comment by MarcinCieslak** [comment]
Hi!
Here are (a bit outdated) instructions:
https://edutechwiki.unige.ch/en/LAMS_installation_and_configuration#LAMS_4.5+

It goes more or less like this:
1. Get prerequisites as in the link
2. Get LAMS v4.8 code
3. Use utf8mb4 character set to create the DB
4. Go through lams_build/*.properties file. If you want to overwrite any setting, put it into lams_build/build.properties. It takes precedence over other .properties files and and is ignored by git.
5. Run deploy-lams Ant target from lams_build/build.xml
6. Start WildFly
